{{- if .Values.mqtt.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hdmi-multiviewer-proxy.fullname" . }}
  labels:
    {{- include "hdmi-multiviewer-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  MQTT_USERNAME: {{ .Values.mqtt.username | quote }}
  MQTT_PASSWORD: {{ .Values.mqtt.password | quote }}
{{- end }}
